#!/usr/bin/env python3
import datetime
import json
import os
import re
import shutil
from pathlib import Path


def slugify(text):
    text = re.sub(r"[\W_]+", "-", text.lower()).strip("-")
    return text


def write_file(filename: str, contents: str):
    with open(filename, "w") as outfile:
        outfile.write(contents)


print("Starting...")
current_dir = Path(__file__).resolve().parent
os.chdir(current_dir)

content_directory = current_dir / "content"
if content_directory.is_dir():
    shutil.rmtree(content_directory)

content_directory.mkdir(exist_ok=True)

write_file(
    "content/_index.md",
    """+++
title = "Main section"
+++
Hello there
""",
)

(current_dir / "content/emails").mkdir(parents=True)

write_file(
    "content/emails/_index.md",
    """+++
title = "Emails section"
template = "emails.html"
sort_by = "title"
+++
""",
)

with open("threads.json") as f:
    for line in f:
        thread = json.loads(line)
        subject = thread["messages"][0]["subject"]
        date = datetime.datetime.strptime(
            thread["messages"][0]["date"], "%Y-%m-%dT%H:%M:%S%z"
        )
        # Convert the date to UTC.
        date = date.astimezone(datetime.timezone.utc)

        dir = (
            content_directory
            / "emails"
            / f"{slugify(subject)}-{date.strftime('%Y-%m-%d')}"
        )
        dir.mkdir(parents=True)
        write_file(
            dir / "_index.md",
            f"""+++
title = "{subject}"
template = "thread.html"
date = {date.strftime("%Y-%m-%dT%H:%M:%SZ")}
+++
""",
        )
        for counter, message in enumerate(thread["messages"], start=1):
            message["date"] = datetime.datetime.strptime(
                message["date"], "%Y-%m-%dT%H:%M:%S%z"
            ).astimezone(datetime.timezone.utc)
            message["body"] = message["body"].replace("\r\n", "\n")
            filename = dir / f"message{counter}.md"
            print(f"Writing {filename.relative_to(current_dir)}...")
            write_file(
                filename,
                f"""+++
date = {message["date"].strftime("%Y-%m-%dT%H:%M:%SZ")}

[extra]
from = "{message["sender"]}"
+++

{message["body"]}
""",
            )

print("Done.")
